//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauEntityFWDbAssign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestTable
    {
        public int RestId { get; set; }
        public string RestName { get; set; }
        public string Cusine { get; set; }
    }
}
